Repository metaspace2020/metaspace, pull requests merged in 2021-07, with the labels that each got.

#881 Add KEGG database
  ansible/aws/templates/all/vars.yml.template
  metaspace/engine/scripts/kegg_importer.py
  metaspace/webapp/src/modules/App/DatabaseHelp.vue
Labels: enhancement

#904 Topic/group approval message
  metaspace/webapp/src/modules/GroupProfile/RequestedAccessDialog.scss
  metaspace/webapp/src/modules/GroupProfile/RequestedAccessDialog.spec.ts
  metaspace/webapp/src/modules/GroupProfile/RequestedAccessDialog.tsx
  metaspace/webapp/src/modules/GroupProfile/ViewGroupPage.vue
  metaspace/webapp/src/modules/GroupProfile/__snapshots__/RequestedAccessDialog.spec.ts.snap
  metaspace/webapp/src/modules/GroupProfile/__snapshots__/ViewGroupPage.spec.ts.snap
  metaspace/webapp/src/modules/MetadataEditor/UploadPage.vue
Labels: enhancement

#908 [Edit page] description update bug
  metaspace/graphql/src/modules/dataset/controller/Mutation.ts
Labels: bug

#900 Ds comparison page improvements #1 after first feedback
  metaspace/webapp/src/modules/Annotations/annotation-widgets/default/MainImageHeader.vue
  metaspace/webapp/src/modules/Datasets/comparison/DatasetComparisonAnnotationTable.scss
  metaspace/webapp/src/modules/Datasets/comparison/DatasetComparisonAnnotationTable.tsx
  metaspace/webapp/src/modules/Datasets/comparison/DatasetComparisonGrid.scss
  metaspace/webapp/src/modules/Datasets/comparison/DatasetComparisonGrid.spec.ts
  metaspace/webapp/src/modules/Datasets/comparison/DatasetComparisonGrid.tsx
  metaspace/webapp/src/modules/Datasets/comparison/DatasetComparisonPage.scss
  metaspace/webapp/src/modules/Datasets/comparison/DatasetComparisonPage.tsx
  metaspace/webapp/src/modules/Datasets/comparison/__snapshots__/DatasetComparisonAnnotationTable.spec.ts.snap
  metaspace/webapp/src/modules/Datasets/comparison/__snapshots__/DatasetComparisonGrid.spec.ts.snap
  metaspace/webapp/src/modules/Datasets/list/__snapshots__/DatasetItem.spec.js.snap
  metaspace/webapp/src/modules/Datasets/list/__snapshots__/DatasetTable.spec.ts.snap
  metaspace/webapp/tests/utils/setupTestFramework.ts
Labels: bug, enhancement
