Repository metaspace2020/metaspace, pull requests merged in 2022-08, with the labels that each got.

#1161 Spotting improvements
  metaspace/engine/lambdas/spotting/lambdaFunction.py
  metaspace/webapp/src/modules/SpottingProject/ChartSettings.tsx
  metaspace/webapp/src/modules/SpottingProject/DashboardHeatmapChart.tsx
  metaspace/webapp/src/modules/SpottingProject/DashboardPage.scss
  metaspace/webapp/src/modules/SpottingProject/DashboardPage.tsx
  metaspace/webapp/src/modules/SpottingProject/DashboardScatterChart.tsx
Labels: enhancement

#1160 Co-localization column display
  metaspace/webapp/src/modules/Annotations/AnnotationTable.vue
  metaspace/webapp/src/modules/Annotations/__snapshots__/AnnotationTable.spec.ts.snap
  metaspace/webapp/src/modules/Project/__snapshots__/DatasetsDialog.spec.ts.snap
Labels: bug

#1171 [MetadataEditor] removed ppm value update on edition
  metaspace/webapp/src/modules/MetadataEditor/MetadataEditor.vue
Labels: bug

#1174 Update Lithops up to 2.7.0
  metaspace/engine/docker/lithops_ibm_ce/Readme.md
  metaspace/engine/docker/lithops_ibm_vpc/Dockerfile
  metaspace/engine/docker/lithops_ibm_vpc/build.sh
  metaspace/engine/docker/lithops_ibm_vpc/build_and_push.sh
  metaspace/engine/requirements.txt
  metaspace/engine/sm/engine/annotation_lithops/executor.py
  metaspace/engine/tests/sci_test/spheroid.py
Labels: infrastructure

#1176 Fixed problem on removing datasets from project
  metaspace/webapp/src/modules/Project/DatasetsDialog.tsx
Labels: bug

#1168 Added intensities export feature
  metaspace/webapp/src/components/IonImageViewer.tsx
  metaspace/webapp/src/components/RoiSettings.tsx
  metaspace/webapp/src/components/__snapshots__/IonImageViewer.spec.ts.snap
  metaspace/webapp/src/lib/formatCsvRow.ts
  metaspace/webapp/src/lib/ionImageRendering.ts
  metaspace/webapp/src/modules/Annotations/AnnotationTable.vue
  metaspace/webapp/src/modules/Annotations/__snapshots__/AnnotationTable.spec.ts.snap
Labels: enhancement

#1180 Co-localization column behavior fixed
  metaspace/graphql/esConnector.ts
  metaspace/graphql/schemas/annotation.graphql
  metaspace/webapp/src/modules/Annotations/AnnotationTable.vue
  metaspace/webapp/src/modules/Annotations/__snapshots__/AnnotationTable.spec.ts.snap
Labels: bug, enhancement

#1175 Imzml browser performance
  metaspace/engine/sm/rest/imzml_browser.py
  metaspace/graphql/schemas/dataset.graphql
  metaspace/graphql/src/modules/dataset/controller/Query.ts
  metaspace/webapp/src/api/dataset.ts
  metaspace/webapp/src/components/MultiChannelController/MultiChannelController.tsx
  metaspace/webapp/src/components/SimpleIonImageViewer/SimpleIonImageViewer.tsx
  metaspace/webapp/src/modules/Datasets/comparison/__snapshots__/DatasetComparisonGrid.spec.ts.snap
  metaspace/webapp/src/modules/Datasets/imzml/DatasetBrowserKendrickPlot.tsx
  metaspace/webapp/src/modules/Datasets/imzml/DatasetBrowserPage.tsx
  metaspace/webapp/src/modules/Datasets/imzml/DatasetBrowserSpectrumChart.tsx
Labels: enhancement
