Repository metaspace2020/metaspace, pull requests merged in 2022-11, with the labels that each got.

#1228 Imzml browser improvements
  metaspace/graphql/src/utils/smApi/smApiCall.ts
  metaspace/webapp/src/components/SimpleIonImageViewer/SimpleIonImageViewer.tsx
  metaspace/webapp/src/modules/Datasets/imzml/DatasetBrowserKendrickPlot.tsx
  metaspace/webapp/src/modules/Datasets/imzml/DatasetBrowserPage.tsx
  metaspace/webapp/src/modules/Datasets/imzml/DatasetBrowserSpectrumChart.tsx
  metaspace/webapp/src/modules/Datasets/overview/DatasetActionsDropdown.tsx
Labels: enhancement

#1229 Fixed group tab tests
  metaspace/webapp/src/modules/Group/__snapshots__/GroupsListItem.spec.ts.snap
  metaspace/webapp/src/modules/Group/__snapshots__/GroupsListPage.spec.ts.snap
Labels: bug

#1230 Removed duplicate groups from group list page
  metaspace/graphql/src/modules/group/controller.ts
  metaspace/webapp/src/modules/Group/GroupsListPage.tsx
Labels: bug

#1239 Change copy ion formula pattern
  metaspace/webapp/src/lib/formulaParser.tsx
  metaspace/webapp/src/modules/Annotations/AnnotationView.ts
  metaspace/webapp/src/modules/Annotations/AnnotationView.vue
  metaspace/webapp/src/modules/Datasets/comparison/DatasetComparisonPage.tsx
  metaspace/webapp/src/modules/Datasets/imzml/DatasetBrowserPage.tsx
Labels: enhancement

#1231 ImzMLError did not move the dataset to FAILED status
  metaspace/engine/sm/engine/daemons/lithops.py
Labels: bug

#1243 [DatasetBrowser] Fix ion image update
  metaspace/webapp/src/modules/Datasets/imzml/DatasetBrowserKendrickPlot.tsx
  metaspace/webapp/src/modules/Datasets/imzml/DatasetBrowserPage.tsx
  metaspace/webapp/src/modules/Datasets/imzml/DatasetBrowserSpectrumChart.tsx
Labels: bug

#1244 Add perform_enrichment variable to python-client
  metaspace/engine/sm/engine/annotation_lithops/annotation_job.py
  metaspace/engine/sm/engine/annotation_lithops/run_enrichment.py
  metaspace/graphql/schemas/dataset.graphql
  metaspace/python-client/metaspace/__init__.py
  metaspace/python-client/metaspace/sm_annotation_utils.py
Labels: python

#1248 [ionImageRendering] fixed grayscale intensities parsing
  metaspace/webapp/src/lib/ionImageRendering.spec.ts
  metaspace/webapp/src/lib/ionImageRendering.ts
Labels: bug

#1246 Update pyimzML to ver. 1.5.3
  metaspace/engine/requirements.txt
Labels: dependencies

#1245 LION improvements after release with feature flag
  metaspace/graphql/schemas/annotation.graphql
  metaspace/graphql/schemas/dataset.graphql
  metaspace/graphql/src/modules/dataset/controller/Dataset.ts
  metaspace/graphql/src/modules/dataset/controller/Mutation.ts
  metaspace/graphql/src/modules/dataset/controller/Query.ts
  metaspace/graphql/src/utils/smApi/datasets.ts
  metaspace/webapp/src/api/dataset.ts
  metaspace/webapp/src/api/metadata.ts
  metaspace/webapp/src/components/NewFeatureBadge/NewFeatureBadge.tsx
  metaspace/webapp/src/modules/Admin/SystemHealthPage.spec.ts
  metaspace/webapp/src/modules/Admin/SystemHealthPage.vue
  metaspace/webapp/src/modules/Annotations/AnnotationTable.vue
  metaspace/webapp/src/modules/Datasets/enrichment/DatasetEnrichmentChart.tsx
  metaspace/webapp/src/modules/Datasets/enrichment/DatasetEnrichmentPage.scss
  metaspace/webapp/src/modules/Datasets/enrichment/DatasetEnrichmentPage.tsx
  metaspace/webapp/src/modules/Datasets/enrichment/DatasetEnrichmentTable.scss
  metaspace/webapp/src/modules/Datasets/enrichment/DatasetEnrichmentTable.tsx
  metaspace/webapp/src/modules/Datasets/imzml/DatasetBrowserKendrickPlot.spec.ts
  metaspace/webapp/src/modules/Datasets/imzml/DatasetBrowserSpectrumChart.spec.ts
  metaspace/webapp/src/modules/Datasets/imzml/__snapshots__/DatasetBrowserKendrickPlot.spec.ts.snap
  metaspace/webapp/src/modules/Datasets/imzml/__snapshots__/DatasetBrowserSpectrumChart.spec.ts.snap
  metaspace/webapp/src/modules/Datasets/overview/DatasetActionsDropdown.tsx
  metaspace/webapp/src/modules/Filters/FilterPanel.vue
  metaspace/webapp/src/modules/Filters/filterSpecs.ts
  metaspace/webapp/src/modules/Filters/url.ts
  metaspace/webapp/src/modules/MetadataEditor/MetadataEditPage.vue
  metaspace/webapp/src/modules/MetadataEditor/MetadataEditor.vue
  metaspace/webapp/src/modules/MetadataEditor/__snapshots__/MetadataEditor.spec.ts.snap
  metaspace/webapp/src/store/getters.js
Labels: bug, enhancement
