Repository metaspace2020/metaspace, pull requests merged in 2022-06, with the labels that each got.

#1122 Wrong function parameters in python-client
  metaspace/python-client/metaspace/__init__.py
  metaspace/python-client/metaspace/sm_annotation_utils.py
Labels: bug, quick task

#1127 Dataset Comparison ShareLink with filter and multichannel bug
  metaspace/webapp/src/modules/Datasets/comparison/DatasetComparisonGrid.tsx
  metaspace/webapp/src/modules/Datasets/comparison/DatasetComparisonPage.tsx
  metaspace/webapp/src/modules/Datasets/comparison/DatasetComparisonShareLink.tsx
Labels: bug, enhancement

#1130 Added reference for NglycDb at Database help page
  metaspace/webapp/src/modules/App/DatabaseHelp.vue
Labels: enhancement
