Repository metaspace2020/metaspace, pull requests merged in 2023-07, with the labels that each got.

#1381 Fixed free text filter
  metaspace/graphql/esConnector.ts
Labels: bug

#1377 Fixed spectrum chart rendering
  metaspace/webapp/src/modules/Datasets/imzml/DatasetBrowserKendrickPlot.tsx
  metaspace/webapp/src/modules/Datasets/imzml/DatasetBrowserSpectrumChart.tsx
Labels: bug

#1376 Hide unused source on Detectability
  metaspace/webapp/src/modules/SpottingProject/DashboardPage.tsx
Labels: quick task

#1386 Change bootstrap FDR type
  metaspace/graphql/src/migrations/1686651472177-LIONFdrTypeChange.ts
Labels: bug

#1385 Fixed custom db pixel intensities download
  metaspace/webapp/src/modules/Annotations/AnnotationTable.vue
  metaspace/webapp/src/modules/Datasets/comparison/DatasetComparisonPage.tsx
Labels: bug

#1389 Change the time before restart lithops daemon
  ansible/roles/sm_lithops_daemon/templates/sm-lithops-daemon.supervisor.j2
Labels: maintenance

#1382 Fixe current row highlight selection
  metaspace/webapp/src/modules/Annotations/AnnotationTable.vue
Labels: bug

#1378 Improved ion image file
  metaspace/webapp/src/components/MultiChannelController/MultiChannelController.tsx
  metaspace/webapp/src/components/SimpleIonImageViewer/SimpleIonImageViewer.tsx
  metaspace/webapp/src/modules/Datasets/comparison/DatasetComparisonGrid.tsx
  metaspace/webapp/src/modules/Datasets/comparison/DatasetComparisonPage.tsx
  metaspace/webapp/src/modules/Datasets/comparison/__snapshots__/DatasetComparisonGrid.spec.ts.snap
  metaspace/webapp/src/modules/ImageViewer/ImageSaver.vue
  metaspace/webapp/src/modules/ImageViewer/ImageViewer.vue
Labels: enhancement

#1373 Removed lcms from webapp
  metaspace/webapp/src/components/IonImageViewer.tsx
  metaspace/webapp/src/modules/Annotations/annotation-widgets/index.ts
  metaspace/webapp/src/modules/Annotations/annotation-widgets/lcms/Diagnostics.vue
  metaspace/webapp/src/modules/Annotations/annotation-widgets/lcms/MainImage.vue
  metaspace/webapp/src/modules/Annotations/annotation-widgets/lcms/MainImageHeader.vue
  metaspace/webapp/src/modules/Annotations/annotation-widgets/lcms/RelatedAnnotations.vue
  metaspace/webapp/src/modules/Annotations/annotation-widgets/lcms/XicPlot.vue
  metaspace/webapp/src/modules/MetadataEditor/UploadPage.vue
Labels: quick task

#1393 [ES] fixed phrase filter
  metaspace/graphql/datasetFilters.js
Labels: enhancement

#1396 Feat/txt search special char bug
  metaspace/graphql/esConnector.ts
Labels: bug

#1395 [Detectability] Added source tabs handled by group permission
  metaspace/engine/scripts/db_schema.sql
  metaspace/graphql/schemas/group.graphql
  metaspace/graphql/src/migrations/1689063013083-DetectabilityPermission.ts
  metaspace/graphql/src/modules/group/controller.ts
  metaspace/graphql/src/modules/group/model.ts
  metaspace/webapp/src/api/user.ts
  metaspace/webapp/src/modules/SpottingProject/DashboardPage.scss
  metaspace/webapp/src/modules/SpottingProject/DashboardPage.tsx
Labels: enhancement

#1397 [EsConnector] added specific search for ds_name using regex
  metaspace/graphql/esConnector.ts
  metaspace/webapp/src/modules/Filters/__snapshots__/FilterPanel.spec.ts.snap
  metaspace/webapp/src/modules/Filters/filter-components/SearchBox.vue
  metaspace/webapp/src/modules/Project/__snapshots__/ProjectsListPage.spec.ts.snap
Labels: bug
