Repository metaspace2020/metaspace, pull requests merged in 2023-10, with the labels that each got.

#1433 Updated ES attributes _term for _key
  metaspace/graphql/src/modules/lookups/controller.ts
Labels: bug

#1439 Sorting metadata filter suggestions
  metaspace/graphql/esConnector.ts
  metaspace/graphql/schemas/group.graphql
  metaspace/graphql/src/modules/group/controller.ts
  metaspace/graphql/src/modules/lookups/controller.ts
  metaspace/webapp/src/api/group.ts
  metaspace/webapp/src/modules/Filters/__snapshots__/FilterPanel.spec.ts.snap
  metaspace/webapp/src/modules/Filters/filter-components/searchableFilterQueries.ts
  metaspace/webapp/src/modules/Group/GroupsListPage.tsx
Labels: bug, enhancement

#1430 Update Lithops up to 3.0.1
  metaspace/engine/conf/config.json.template
  metaspace/engine/docker/lithops_ibm_ce/Dockerfile
  metaspace/engine/docker/lithops_ibm_ce/Readme.md
  metaspace/engine/docker/lithops_ibm_vpc/Dockerfile
  metaspace/engine/requirements.txt
  metaspace/engine/sm/engine/annotation_lithops/executor.py
Labels: infrastructure
