Repository metaspace2020/metaspace, pull requests merged in 2023-03, with the labels that each got.

#1313 Showing selected FDR at Dataset browser page
  metaspace/webapp/src/modules/Datasets/imzml/DatasetBrowserKendrickPlot.scss
  metaspace/webapp/src/modules/Datasets/imzml/DatasetBrowserKendrickPlot.tsx
  metaspace/webapp/src/modules/Datasets/imzml/DatasetBrowserPage.tsx
  metaspace/webapp/src/modules/Datasets/imzml/DatasetBrowserSpectrumChart.scss
  metaspace/webapp/src/modules/Datasets/imzml/DatasetBrowserSpectrumChart.tsx
Labels: enhancement, quick task

#1317 [DatasetOverview] hiding additional information field
  metaspace/webapp/src/modules/Datasets/overview/DatasetOverviewPage.tsx
Labels: bug, quick task

#1286 Feat/uppy behaviour improvement
  metaspace/graphql/config/config.js.template
  metaspace/graphql/config/default.js
  metaspace/graphql/config/development.docker.js
  metaspace/graphql/config/test.js
  metaspace/graphql/package.json
  metaspace/graphql/src/modules/webServer/datasetUploadMiddleware.spec.ts
  metaspace/graphql/src/modules/webServer/datasetUploadMiddleware.ts
  metaspace/graphql/src/modules/webServer/getCompanionOptions.ts
  metaspace/graphql/src/utils/config.ts
  metaspace/graphql/yarn.lock
  metaspace/python-client/metaspace/__init__.py
  metaspace/python-client/metaspace/sm_annotation_utils.py
  metaspace/webapp/src/components/UppyUploader/UppyUploader.vue
  metaspace/webapp/src/modules/MetadataEditor/UploadPage.vue
Labels: enhancement

#1304 Spotting improvements pre-release
  metaspace/webapp/src/assets/inline/refactoring-ui/icon-folder-download.svg
  metaspace/webapp/src/modules/App/MetaspaceHeader.vue
  metaspace/webapp/src/modules/SpottingProject/DashboardHeatmapChart.tsx
  metaspace/webapp/src/modules/SpottingProject/DashboardPage.tsx
  metaspace/webapp/src/modules/SpottingProject/DashboardScatterChart.scss
  metaspace/webapp/src/modules/SpottingProject/DashboardScatterChart.tsx
  metaspace/webapp/src/router.ts
Labels: enhancement

#1234 Add size and hash of imzML/ibd files to PostgreSQL
  metaspace/engine/scripts/db_schema.sql
  metaspace/engine/sm/engine/annotation_lithops/annotation_job.py
  metaspace/engine/sm/engine/annotation_lithops/load_ds.py
  metaspace/engine/sm/engine/annotation_lithops/pipeline.py
  metaspace/graphql/src/migrations/1667433292010-SizeHash.ts
  metaspace/graphql/src/modules/engine/model.ts
Labels: enhancement

#1323 Added METASPACE stats to home page
  metaspace/graphql/config/config.js.template
  metaspace/graphql/package.json
  metaspace/graphql/schemas/group.graphql
  metaspace/graphql/schemas/user.graphql
  metaspace/graphql/src/modules/group/controller.ts
  metaspace/graphql/src/modules/user/controller.ts
  metaspace/graphql/src/utils/config.ts
  metaspace/webapp/src/api/group.ts
  metaspace/webapp/src/api/user.ts
  metaspace/webapp/src/components/PrimaryIcon.vue
  metaspace/webapp/src/modules/App/AboutPage.scss
  metaspace/webapp/src/modules/App/AboutPage.tsx
  metaspace/webapp/src/modules/App/AboutPage.vue
  metaspace/webapp/src/modules/App/PublicationItem.tsx
  metaspace/webapp/src/modules/App/PublicationItem.vue
  metaspace/webapp/src/modules/App/PublicationsPage.scss
  metaspace/webapp/src/modules/App/PublicationsPage.spec.ts
  metaspace/webapp/src/modules/App/PublicationsPage.tsx
  metaspace/webapp/src/modules/App/PublicationsPage.vue
  metaspace/webapp/src/modules/App/__snapshots__/PublicationsPage.spec.ts.snap
  metaspace/webapp/src/router.ts
Labels: enhancement

#1325 LION release
  metaspace/graphql/src/modules/dataset/controller/Mutation.spec.ts
  metaspace/graphql/src/modules/dataset/controller/Mutation.ts
  metaspace/webapp/src/lib/config.ts
  metaspace/webapp/src/modules/Datasets/enrichment/DatasetEnrichmentChart.tsx
  metaspace/webapp/src/modules/Datasets/enrichment/DatasetEnrichmentPage.tsx
  metaspace/webapp/src/modules/Datasets/enrichment/DatasetEnrichmentTable.tsx
  metaspace/webapp/src/modules/Datasets/overview/DatasetActionsDropdown.spec.ts
  metaspace/webapp/src/modules/Datasets/overview/__snapshots__/DatasetActionsDropdown.spec.ts.snap
  metaspace/webapp/src/modules/Filters/__snapshots__/FilterPanel.spec.ts.snap
  metaspace/webapp/src/modules/MetadataEditor/MetadataEditPage.vue
  metaspace/webapp/src/modules/MetadataEditor/__snapshots__/MetadataEditor.spec.ts.snap
  metaspace/webapp/src/modules/MetadataEditor/inputs/EnrichmentHelp.vue
Labels: enhancement
