Repository metaspace2020/metaspace, pull requests merged in 2024-11, with the labels that each got.

#1592 Implement User Access Control with Plans Schema and API Usage Logging
  metaspace/engine/scripts/db_schema.sql
  metaspace/engine/tests/conftest.py
  metaspace/engine/tests/test_api_databases.py
  metaspace/engine/tests/test_es_export.py
  metaspace/graphql/bin/generate-json-graphql-schema.js
  metaspace/graphql/config/test.js
  metaspace/graphql/executableSchema.ts
  metaspace/graphql/schema.ts
  metaspace/graphql/schemas/plan.graphql
  metaspace/graphql/schemas/user.graphql
  metaspace/graphql/src/context.ts
  metaspace/graphql/src/getContext.ts
  metaspace/graphql/src/migrations/1727982165857-ApiUsage.ts
  metaspace/graphql/src/modules/auth/controller.ts
  metaspace/graphql/src/modules/dataset/controller/Dataset.ts
  metaspace/graphql/src/modules/dataset/controller/Mutation.ts
  metaspace/graphql/src/modules/dataset/controller/PlanDatasetCrud.spec.ts
  metaspace/graphql/src/modules/plan/controller/Mutation.spec.ts
  metaspace/graphql/src/modules/plan/controller/Mutation.ts
  metaspace/graphql/src/modules/plan/controller/Query.spec.ts
  metaspace/graphql/src/modules/plan/controller/Query.ts
  metaspace/graphql/src/modules/plan/controller/index.ts
  metaspace/graphql/src/modules/plan/model.ts
  metaspace/graphql/src/modules/plan/util/canPerformAction.spec.ts
  metaspace/graphql/src/modules/plan/util/canPerformAction.ts
  metaspace/graphql/src/modules/user/__snapshots__/controller.spec.ts.snap
  metaspace/graphql/src/modules/user/controller.spec.ts
  metaspace/graphql/src/modules/user/controller.ts
  metaspace/graphql/src/modules/user/model.ts
  metaspace/graphql/src/tests/graphqlTestEnvironment.ts
  metaspace/graphql/src/tests/testDataCreation.ts
  metaspace/graphql/src/utils/typeOrmConfig.ts
  metaspace/python-client/metaspace/sm_annotation_utils.py
  metaspace/webapp/src/api/graphqlClient.ts
  metaspace/webapp/src/api/user.ts
  metaspace/webapp/src/modules/Datasets/list/DownloadDialog.tsx
  metaspace/webapp/src/modules/Datasets/list/__snapshots__/DownloadDialog.spec.ts.snap
  metaspace/webapp/src/modules/Datasets/overview/DatasetActionsDropdown.spec.ts
  metaspace/webapp/src/modules/Datasets/overview/DatasetActionsDropdown.tsx
  metaspace/webapp/tests/utils/graphql-schema.json
Labels: enhancement

#1593 Added more strict download policies
  metaspace/engine/scripts/db_schema.sql
  metaspace/graphql/schemas/plan.graphql
  metaspace/graphql/src/migrations/1730826426836-DefaultPlan.ts
  metaspace/graphql/src/modules/auth/operation.ts
  metaspace/graphql/src/modules/dataset/controller/Dataset.ts
  metaspace/graphql/src/modules/dataset/controller/PlanDatasetCrud.spec.ts
  metaspace/graphql/src/modules/plan/model.ts
  metaspace/graphql/src/modules/plan/util/canPerformAction.ts
  metaspace/webapp/src/modules/Datasets/list/DownloadDialog.tsx
  metaspace/webapp/src/modules/Datasets/overview/DatasetActionsDropdown.tsx
  metaspace/webapp/tests/utils/graphql-schema.json
Labels: bug, enhancement

#1594 Fixing a bug related to RAM limits for process_centr_segment step
  metaspace/engine/sm/engine/annotation_lithops/annotate.py
  metaspace/engine/sm/engine/annotation_lithops/executor.py
  metaspace/engine/sm/engine/annotation_lithops/pipeline.py
Labels: bug

#1596 Updated google passport lib
  metaspace/graphql/package.json
  metaspace/graphql/yarn.lock
Labels: quick task

#1600 Exclude chem_mods and neutral losses from decoy selection
  metaspace/engine/sm/engine/annotation/fdr.py
Labels: bug
