Repository metaspace2020/metaspace, pull requests merged in 2024-03, with the labels that each got.

#1494 Added .ibd file size limit
  metaspace/webapp/src/lib/config.ts
  metaspace/webapp/src/modules/MetadataEditor/UploadPage.vue
Labels: enhancement

#1492 Cost calculation script + cloudwatch bugfix
  metaspace/engine/scripts/update_perf_profile_costs.py
  metaspace/engine/sm/engine/annotation_lithops/executor.py
  metaspace/engine/sm/engine/daemons/dataset_manager.py
  metaspace/engine/sm/engine/daemons/lithops.py
  metaspace/engine/sm/engine/postprocessing/cloudwatch.py
Labels: bug, python

#1498 Changes to the structure of saving models and the list of datasets
  metaspace/scoring-models/datasets/v1.2022-01-15/training.csv
  metaspace/scoring-models/datasets/v2.2023-05-17/testing.csv
  metaspace/scoring-models/datasets/v2.2023-05-17/training.csv
  metaspace/scoring-models/datasets/v2.2023-12-14/testing.csv
  metaspace/scoring-models/datasets/v2.2023-12-14/training.csv
  metaspace/scoring-models/models_default/v2.2023-12-14_(METASPACE-ML_Animal).cbm
  metaspace/scoring-models/models_default/v2.2023-12-14_(METASPACE-ML_Plant).cbm
  metaspace/scoring-models/models_old/v1.2022-01-05_(METASPACE-ML_Lachlan).cbm
  metaspace/scoring-models/models_old/v2.2023-05-17_(METASPACE-ML).cbm
Labels: enhancement, quick task
