Repository metaspace2020/metaspace, pull requests merged in 2024-02, with the labels that each got.

#1455 [CustomDatabase] added feature to enable public custom database
  metaspace/engine/scripts/db_schema.sql
  metaspace/engine/sm/engine/molecular_db.py
  metaspace/graphql/schemas/moldb.graphql
  metaspace/graphql/src/migrations/1702034438960-PublicCustomDatabase.ts
  metaspace/graphql/src/modules/dataset/controller/Mutation.ts
  metaspace/graphql/src/modules/moldb/MolecularDbRepository.ts
  metaspace/graphql/src/modules/moldb/model.ts
  metaspace/graphql/src/utils/smApi/databases.ts
  metaspace/webapp/src/api/group.ts
  metaspace/webapp/src/api/moldb.ts
  metaspace/webapp/src/modules/MolecularDatabases/DatabaseDetails.scss
  metaspace/webapp/src/modules/MolecularDatabases/DatabaseDetailsForm.tsx
  metaspace/webapp/src/modules/MolecularDatabases/DatabasesTable.tsx
  metaspace/webapp/src/modules/MolecularDatabases/UploadDialog.tsx
  metaspace/webapp/src/modules/MolecularDatabases/__snapshots__/MolecularDatabases.spec.ts.snap
  metaspace/webapp/src/modules/MolecularDatabases/formatting.ts
Labels: enhancement

#1473 Fixed share link for reprocessed datasets
  metaspace/webapp/src/modules/ImageViewer/useRestoredState.ts
Labels: bug

#1475 [Detectability] Fixed subclass disabled
  metaspace/webapp/src/modules/SpottingProject/DashboardPage.tsx
Labels: bug

#1478 Bump version of python-client
  metaspace/python-client/metaspace/__init__.py
Labels: quick task, python

#1479 Update python-client action workflow
  .github/workflows/pythonpublish.yml
Labels: infrastructure

#1442 Run pipeline on AWS
  ansible/aws/templates/all/vars.yml.template
  metaspace/engine/.dockerignore
  metaspace/engine/conf/config.json.template
  metaspace/engine/docker/lithops_aws_ec2/Dockerfile
  metaspace/engine/docker/lithops_aws_ec2/build_and_push.sh
  metaspace/engine/docker/lithops_aws_lambda/Dockerfile
  metaspace/engine/docker/lithops_aws_lambda/build_and_push.sh
  metaspace/engine/requirements.txt
  metaspace/engine/sm/engine/annotation_lithops/annotation_job.py
  metaspace/engine/sm/engine/annotation_lithops/build_moldb.py
  metaspace/engine/sm/engine/annotation_lithops/executor.py
  metaspace/engine/sm/engine/annotation_lithops/load_ds.py
  metaspace/engine/sm/engine/annotation_lithops/pipeline.py
  metaspace/engine/sm/engine/annotation_lithops/store_images.py
  metaspace/engine/sm/engine/daemons/dataset_manager.py
  metaspace/engine/sm/engine/postprocessing/colocalization.py
  metaspace/engine/sm/engine/postprocessing/ds_size_hash.py
  metaspace/engine/tests/annotation_lithops/test_annotation_job.py
Labels: infrastructure, python

#1481 Update lithops up to 3.1.1
  metaspace/engine/requirements.txt
  metaspace/engine/sm/engine/postprocessing/colocalization.py
Labels: infrastructure

#1480 Reissue of SSL certificate 2024
  ansible/aws/files/metaspace2020_eu.pem
Labels: infrastructure

#1483 Run METASPACE-aws on docker
  .circleci/config.yml
  docker/docker-compose.yml
  metaspace/engine/conf/config.docker.json
  metaspace/engine/conf/test_config.json
  metaspace/engine/sm/engine/annotation_lithops/annotation_job.py
  metaspace/engine/sm/engine/annotation_lithops/executor.py
  metaspace/engine/sm/engine/annotation_lithops/load_ds.py
  metaspace/engine/sm/engine/annotation_lithops/pipeline.py
  metaspace/engine/sm/engine/daemons/dataset_manager.py
  metaspace/engine/sm/engine/postprocessing/ds_size_hash.py
  metaspace/engine/tests/conftest.py
  metaspace/graphql/esConnector.ts
  metaspace/graphql/src/modules/dataset/controller/Query.ts
  metaspace/graphql/src/modules/group/controller.ts
Labels: bug, enhancement
